### ISSUE TITLE
Hot reload crashes on swift 3 / iOS 10 when there is a path in the URL

### ISSUE THREAD

**Issue by aldeed** [meteor/cordova-plugin-meteor-webapp#12] opened 2016-09-09 18:43 UTC
Moved this discussion from https://github.com/meteor/cordova-plugin-meteor-webapp/pull/11

Using the swift 3 version of this plugin, `window.location.reload()` and `window.location.replace(window.location.href)` both crash our app, so hot reloads crash the app. But when you reopen it, it's at the new version. So other than the pesky crash in the middle, hot reloads work. I can reproduce this by just connecting through the Safari console and entering `window.location.reload()` manually. Crashes every time. The error message says it's looking for a local file named "/jobs", which does not exist. /jobs is the route it's on when hot reloading.

I'm thinking it might be a problem with the built in web server. Maybe it needs to be updated to properly serve the app even if there are extra path components.

As a workaround, the hot reload works without crashing when I replace the `window.location.replace(window.location.href)` call with:

``` js
const urlSansPath = `${window.location.protocol}//${window.location.host}/`;
window.location.replace(urlSansPath);
```

**Comment by martijnwalraven** [comment] 2016-09-09 18:47
Is there any way we can can a better understanding of why reloading crashes the app? I suspect what is going on is in some way unique to your app or a specific component (router?) because I haven't seen these crashes either running the tests or with our example apps.

**Comment by aldeed** [comment] 2016-09-09 18:59
I can try making a reproduction. We're using the default wkwebview and react router. I would not be at all surprised if it were something specific to the app. There isn't anything helpful in the logs.

Do the tests test reloading while on a non-root path?

**Comment by martijnwalraven** [comment] 2016-09-09 19:07
The tests run in [https://github.com/apache/cordova-plugin-test-framework](cordova-plugin-test-framework) and use `fetch()` to simulate browser requests (see [here](https://github.com/meteor/cordova-plugin-meteor-webapp/blob/master/tests/www/tests.js) if you're curious). So it is definitely not similar to running an actual app, but it does test quite a few scenarios (including requesting non-existing files and checking that you still get the index page for example, which is needed to support arbitrary paths).

I've also just tested reloading on the boilerplate app ('meteor create ...`), while setting a path. And that seems to work fine. So it would be great if you had a reproduction, because this does sound like a serious issue that we need to look into.

**Comment by aldeed** [comment] 2016-09-09 19:13
OK, might not get to it until next week. One thing I've noticed is that uncaught errors in some places seem to crash the app. I'm not sure if this is just how wkwebview works intentionally. The problem is that when it crashes, it disconnects the Safari console, so you can never see what the javascript error was. So I'm thinking maybe the page reload works but there is some uncaught react router error as soon as it starts to load when we're requesting a non-root route.

**Comment by tafelito** [comment] 2016-09-28 22:21
Hi guys, I'm having a similar issue, but instead of crashing, my app is doing nothing when doing `window.location.replace(window.location.href)`. It does work if I use what @aldeed said instead, it does reload the app in that case. I don't see any error or anything that might be causing this issue. I tried also with `window.location.reload()` but in my case, this one also works.

Any ideas why this could be happening?

I'm using meteor 1.4.1.1 with iOS 10

**Comment by sferoze** [comment] 2017-03-08 22:19
@tafelito my cordova app also seems to not reload anymore since updating to 1.4. When the new version is downloaded the page freezes instead of reloading. If you completely close the iOS app, and then reopen, the new version is loaded. But if the user is behind a version and opens the app, it will freeze when the new code tries to reload...

where did you place `window.location.reload()` It seems like that what my apps needs to do once the new code is downloaded.

**Comment by sferoze** [comment] 2017-03-09 00:14
I tried window.location.reload() as @aldeed mentioned and it crashes the app as well. 

I am experiencing the same issue as @aldeed

**Comment by sferoze** [comment] 2017-03-09 00:26
@aldeed I have been looking through the code and the previous issue you referenced but I don't understand where you placed

```
const urlSansPath = `${window.location.protocol}//${window.location.host}/`;
window.location.replace(urlSansPath);
```

To fix this issue. Please let me know where this code goes.

**Comment by tafelito** [comment] 2017-03-09 01:15
@sferoze did you try using jamielob/reloader package? I'm using that and it's working fine in 1.4.2

**Comment by sferoze** [comment] 2017-03-09 01:20
@tafelito 

Did you have to edit the source code of the reloader package? As you mentioned before? 

I checked out the reload function in that package and made the change that is supposed to fix it... 

replacing `window.location.replace(window.location.href)` with

```
const urlSansPath = `${window.location.protocol}//${window.location.host}/`;
window.location.replace(urlSansPath);
```

**Comment by tafelito** [comment] 2017-03-09 01:41
No need to update, they already committed the change a while ago

**Comment by sferoze** [comment] 2017-03-09 01:43
@tafelito thanks so much for the info! This is a serious bug, without the reloader package, hot code push is broken

**Comment by aldeed** [comment] 2017-03-20 23:08
We actually ended up turning off hot reload on that app, partially because it was not reliable, so I'm not able to offer much more help on this issue.

**Comment by hwillson** [comment] 2018-01-17 19:20
There have been many new releases of Meteor since this issue was created. Please try using a more recent version (>= 1.6.x), and post back if you're still encountering issues. Thanks!

**Closed by hwillson** 2018-01-17 19:20 UTC
