### ISSUE TITLE
Meteor-Cordova iOS app - After some time in bg app completely loses connection to a local web server - http://localhost:{myPortNumber}

### ISSUE THREAD

**Issue by grundmanise** [meteor/cordova-plugin-meteor-webapp#27] opened 2017-02-07 11:31 UTC
I subbmited [this issue](https://github.com/meteor/meteor/issues/8324) on the meteor/meteor, but it is also relevant here.

**Comment by johnthepink** [comment] 2017-02-07 14:58
@grundmanise Possibly will be fixed by #25 ?

**Comment by grundmanise** [comment] 2017-02-07 15:24
@johnthepink It helps with some other bugs.. but not with this one. In my `cordova-plugin-meteor-webapp` fork I've already included this fix...

**Comment by grundmanise** [comment] 2017-02-07 15:32
I am also receiving this error in Safari console: `Failed to load resource: Could not connect to the server. http://localhost:12608/app/ec7e4a948f52773422be6bce9a7e92676be748dd.map`. And some svg icons aren't loading after my app was some time in bg state.

**Comment by macrozone** [comment] 2017-05-22 09:14
@grundmanise: I saw that you created a fork with a workaround for this issue: 

https://github.com/grundmanise/cordova-plugin-meteor-webapp/commit/9a414d88f8a84249009e22d663298fd2dcbb6eab

did this help in your case? did you also apply  https://github.com/meteor/cordova-plugin-meteor-webapp/pull/25 ?

**Comment by grundmanise** [comment] 2017-05-22 09:50
@macrozone Yes, I've also applied #25 (https://github.com/grundmanise/cordova-plugin-meteor-webapp/commit/011d9e8086628861d5b37c5aa26f71ac70f986de)
No, unfortunately it did not solve my issue. But you can try, maybe it will fix you issue.

**Comment by macrozone** [comment] 2017-06-06 13:40
@grundmanise I could reproduce & fix this bug on my reproduction app by applying https://github.com/swisspol/GCDWebServer/pull/299

It happend on my app when i locked the app. I think it only happens if you have also https://github.com/meteor/cordova-plugin-meteor-webapp/pull/25

See the full story: 
https://github.com/meteor/meteor/issues/8763

You can test this version: 

cordova-plugin-meteor-webapp@https://github.com/panter/cordova-plugin-meteor-webapp.git#7bb095ce393d17f662cc6bb596ce91acf743d17a

see ALSO https://github.com/meteor/cordova-plugin-meteor-webapp/pull/30

**Comment by Nauzer** [comment] 2017-09-14 13:09
I'm seeing two pull requests in this repo that try to solve this issue. Any help needed?
I'm experiencing the same issue which also breaks hot code push on iOS.

**Comment by macrozone** [comment] 2017-09-14 13:17
@Nauzer can you try the fork above? 

cordova-plugin-meteor-webapp@https://github.com/panter/cordova-plugin-meteor-webapp.git#7bb095ce393d17f662cc6bb596ce91acf743d17a

**Comment by Nauzer** [comment] 2017-09-21 09:51
@macrozone that seems to work.
However, also does downgrading 1.4.1. What is the benefit of using the branch including your [commit](https://github.com/panter/cordova-plugin-meteor-webapp/commit/c4de08ac11a8125631607779724b6f9a9d67977c)?

**Comment by KoenLav** [comment] 2017-09-26 14:30
In our application we are experiencing similar issues.

We've tried pretty much all forks of this repo, but none seem to fix the problem for us.

Symptoms: after some time in sleep, or after switching to another app, and switching back (on) the connection to the local server is lost and the user is logged out.

Any thoughts?

**Comment by KoenLav** [comment] 2017-10-21 12:01
The issue seems fixed in Meteor 1.5.2.2?

**Comment by deeeed** [comment] 2017-10-21 13:12
not fixed for me in 1.5.2.2

**Comment by rioadrian** [comment] 2017-11-15 09:04
I got this issue to using meteor 1.6

**Comment by Nauzer** [comment] 2017-11-15 10:15
Downgrade cordova-plugin-meteor-webapp to 1.4.1 or use the abovementioned
fork.

On 15 Nov 2017 10:04, "ryo" <notifications@github.com> wrote:

I got this issue to using meteor 1.6

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/meteor/cordova-plugin-meteor-webapp/issues/27#issuecomment-344529048>,
or mute the thread

**Comment by KoenLav** [comment] 2018-01-22 19:23
This issue seems to accurately describe the problem experienced here, it also suggests disabling the suspension of GCDWebServer and creating a background task:

https://github.com/swisspol/GCDWebServer/issues/131

**Closed** 2018-01-23 22:31 UTC
Labels: bug, confirmed

**Comment by Wade-BuildOtto** [comment] 2019-12-03 19:17
I am still seeing this happen on IOS 13.2.3 with Meteor 1.8.1 with 
cordova-plugin-meteor-webapp 1.6.5 
local server crashes images fail to load on page.

**Comment by filipenevola** [comment] 2019-12-11 14:11
Hi @Wade-BuildOtto as this is a very old issue, could you open a new one with steps to reproduce your problem?

**Comment by rioadrian** [comment] 2019-12-12 08:54
Hi I fix my issue using [THIS](https://github.com/NUDelta/cordova-plugin-meteor-webapp/commit/f16159ade362acc8ed0138e615e37c22b20cab98 ) way maybe it can help :)
