### ISSUE TITLE
Uncaught SyntaxError: Unexpected token =>

### ISSUE THREAD

**Issue by killerchip** [meteor/cordova-plugin-meteor-webapp#72] opened 2019-01-29 14:36 UTC
This is an issue that I was able to reproduce in Android Emulator with API 22. Unfortunately I don't have a physical device with API 22 (Android 5.1).

**How to reproduce the issue**

1. Create a new app even with `meteor create` command. In my case it created a `1.8.0.2` app.
1. Add the `android` platform
1. Add `cordova-plugin-meteor-webapp`: `meteor add cordova:cordova-plugin-meteor-webapp@1.6.4` (the issue is there already from 1.6.1).
1. Fire up the Emulator
1. Run the app with `meteor run android`.
1. The app is launched, but it never gets past the splashscreen.

If you connect with Chrome DevTools you will see in console the message above.

**Notes**

* The issue is not reproducible in API 23 (Android 6.0) and above
* I cannot confirm yet (but I strongly suspect) that it is reproducible with API version below 22 also.

**Comment by killerchip** [comment] 2019-01-30 14:21
Further update...
The actual error that relates to the above behavior is:
`Module cordova-plugin-meteor-webapp.WebAppLocalServer does not exist.`.

So when the issue appears, the above message appears in console and the app won't get past the splashscreen.

I can confirm that this behavior is only for Android 4.4.x devices. I was not able to reproduce on 5.1.x physical devices.

**Comment by Nauzer** [comment] 2019-02-04 14:42
Issue is reproducible also on Meteor 1.8.1.beta.15

**Comment by Nauzer** [comment] 2019-02-04 15:36
Seems to be that on of the changes implemented for fixing the HCP issues introduced a fat-arrow function in webapp_local_server.js. (ES6) Imcompatible with Android 4.4.X Chromium version. I guess because  the code is part of the plugin code (not the runtime js) and is therefore not being picked up by Babel (?). 

Anyway I think it is good to fallback to non-ES6 code here since the rest of the file is also not using ES6 syntax.

**Comment by benjamn** [comment] 2019-02-04 15:50
Should be fixed by #73. Thanks @killerchip and @Nauzer!

**Closed** 2019-02-27 01:54 UTC
